version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend
    ports:
      - 9000:3000
    
  backend:
    image: poohcom1/twitter-art-collection-backend:latest
    env_file:
      - .env
    environment:
      - PORT=8080